services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: salon-reservation-php-app:latest
    container_name: salon-reservation-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
    networks:
      - salon-reservation-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: salon-reservation-nginx
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - ./laravel-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - salon-reservation-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: salon-reservation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: salon_reservation
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: salon_user
      MYSQL_PASSWORD: salon_password
    ports:
      - "3307:3306"
    volumes:
      - salon-reservation-db-data:/var/lib/mysql
    networks:
      - salon-reservation-network

  adminer:
    image: adminer:latest
    container_name: salon-reservation-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - salon-reservation-network
    depends_on:
      - db

networks:
  salon-reservation-network:
    driver: bridge

volumes:
  salon-reservation-db-data:
    driver: local
